apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: channel-carrier-allchannel
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: channel-carrier-allchannel
  chart:
    git: git@github.com:usnistgov/blossom.git
    ref: baf-east-1
    path: platforms/hyperledger-fabric/charts/create_channel   
  values:
    metadata:
      namespace: carrier-net
      network:
        version 1.4.4
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://ip-10-10-201-117.ec2.internal:31524
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer 
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel
    orderer:
      address: orderer1.supplychain-net.svc.cluster.local:7050
    channeltx: |-
      CrQDChgKFggCGgYI3fD/gQYiCmFsbGNoYW5uZWwSlwMKlAMKCmFsbGNoYW5uZWwSZhJUCgtBcHBs
      aWNhdGlvbhJFEhMKD21hbnVmYWN0dXJlck1TUBIAEg4KCmNhcnJpZXJNU1ASABIMCghzdG9yZU1T
      UBIAEhAKDHdhcmVob3VzZU1TUBIAGg4KCkNvbnNvcnRpdW0SABqdAhLxAQoLQXBwbGljYXRpb24S
      4QEIARIQCgx3YXJlaG91c2VNU1ASABITCg9tYW51ZmFjdHVyZXJNU1ASABIOCgpjYXJyaWVyTVNQ
      EgASDAoIc3RvcmVNU1ASABokCgxDYXBhYmlsaXRpZXMSFBIKCggKBFYxXzESABoGQWRtaW5zIiIK
      BkFkbWlucxIYEg4IAxIKCgZBZG1pbnMQAhoGQWRtaW5zIiIKB1JlYWRlcnMSFxINCAMSCQoHUmVh
      ZGVycxoGQWRtaW5zIiIKB1dyaXRlcnMSFxINCAMSCQoHV3JpdGVycxoGQWRtaW5zKgZBZG1pbnMa
      JwoKQ29uc29ydGl1bRIZEhcKFVN1cHBseUNoYWluQ29uc29ydGl1bQ==