apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: instantiate-carrier-allchannel-fabcar0
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: instantiate-carrier-allchannel-fabcar0
  chart:
    git: git@github.com:usnistgov/blossom.git
    ref: baf-gitops-blossom
    path: platforms/hyperledger-fabric/charts/instantiate_chaincode
  values:
    metadata:
      namespace: carrier-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    peer:
      name: peer0
      address: peer0.carrier-net:7051
      localmspid: carrierMSP
      loglevel: debug
      tlsstatus: true
    vault:
      role: vault-role
      address: http://ip-10-20-201-64.us-east-2.compute.internal:30358
      authpath: carrier-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/carrier-net/users/admin 
      orderersecretprefix: secret/crypto/peerOrganizations/carrier-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred
      tls: false
    orderer:
      address: orderer1.supplychain-net.svc.cluster.local:7050
    chaincode:
      builder: hyperledger/fabric-ccenv:1.4.4
      name: fabcar
      lang: golang
      version: 0
      instantiationarguments: ''
      endorsementpolicies:  ''
    channel:
      name: allchannel