apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: joinchannel-peer0-join-allchannel-warehouse-peer0
  namespace: warehouse-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: joinchannel-peer0-join-allchannel-warehouse-peer0
  chart:
    git: git@github.com:usnistgov/blossom.git
    ref: baf-gitops-blossom
    path: platforms/hyperledger-fabric/charts/join_channel
  values:
    metadata:
      namespace: warehouse-net
      images:
        fabrictools: hyperledger/fabric-tools:1.4.4
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0

    peer:
      name: peer0
      address: peer0.warehouse-net.org3ambassador.blockchaincloudpoc.com:8443
      localmspid: warehouseMSP
      loglevel: debug
      tlsstatus: true

    vault:
      role: vault-role
      address: http://ip-10-20-201-64.us-east-2.compute.internal:30358
      authpath: warehouse-net-auth
      adminsecretprefix: secret/crypto/peerOrganizations/warehouse-net/users/admin
      orderersecretprefix: secret/crypto/peerOrganizations/warehouse-net/orderer
      serviceaccountname: vault-auth
      imagesecretname: regcred

    channel:
      name: allchannel      
    orderer:
      address: orderer1.supplychain-net.svc.cluster.local:7050

