apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: carrier-net-ca
  namespace: carrier-net
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: carrier-net-ca
  chart:
    git: git@github.com:philmillwee2/baf-test.git
    ref: pmillwee-baf-test2
    path: platforms/hyperledger-fabric/charts/ca    
  values:
    metadata:
      namespace: carrier-net
      images:
        alpineutils: index.docker.io/hyperledgerlabs/alpine-utils:1.0
        ca: hyperledger/fabric-ca:1.4.4
    server:
      name: ca
      tlsstatus: true
      admin: carrier-admin
    storage:
      storageclassname: carriersc
      storagesize: 512Mi
    vault:
      role: vault-role
      address: http://ip-10-20-200-244.us-east-2.compute.internal:32387
      authpath: carrier-net-auth
      secretcert: secret/crypto/peerOrganizations/carrier-net/ca?ca.carrier-net-cert.pem
      secretkey: secret/crypto/peerOrganizations/carrier-net/ca?carrier-net-CA.key
      secretadminpass: secret/credentials/carrier-net/ca/carrier?user
      serviceaccountname: vault-auth
      imagesecretname: regcred
    service:
      servicetype: ClusterIP
      ports:
        tcp:
          port: 7054
    proxy:
      provider: haproxy
      type: peer
